### ISSUE TITLE
No shows start..

### ISSUE THREAD

**Issue by psonnosp** [kodi-svtplay/xbmc-svtplay#207] opened 2017-05-17 00:22 UTC
..but maybe its just my setup that's acting up or is it something in general?

I have version 17.1 Git:20170320-fc1619b on a Win10 machine. 
Log: https://pastebin.com/D2hCKxbU

**Comment by linqcan** [comment] 2017-05-17 18:33
Could you please describe the steps necessary to reproduce this issue?
Thanks!

**Comment by psonnosp** [comment] 2017-05-17 20:40
Oh, thought all that mumbo jumbo in the log could tell you that but I'm a total noob so what do I know :D
Not much steps to describe. I browsed my way to the show in the 'Latest program' menu and tried to start it. That's about it.
Tried to start a few more episodes of different shows at the same time but none would start so kind of thought that the whole thing wasn't working.
But today I checked some more and a few work but the most of them, 95%, generate that same error or no error at all, they just don't start without a error showing up on the screen. And it doesn't seem to matter from under what menu you try to start it.
But regarding how severe the problem is I guess it's just something in my end cause if this happened to everyone I guess there would be some more noise in here.

**Comment by linqcan** [comment] 2017-05-18 19:51
Thanks for the description!

As you have figured out I am unable to reproduce this error.

The error log would indicate some kind of network error causing the payload to be corrupt. Do you use any Man In The Middle (MITM) services such as VPN or do you suffer from an unstable network connection in general?

**Comment by psonnosp** [comment] 2017-05-18 19:59
Nope, have a very stable 250/100 fiber connection  and SVTplay works great in every other way I try to watch on dif fervent units, even in a browser on the same PC that Kodi runs on.
Tried uninstall/install the add on without any change. Would doing the same thing with Kodi perhaps solve it or are there other things to try first?

**Comment by bddali** [comment] 2017-05-21 08:59
I have the same issue, with Kodi 16.1 on a Minix X8-H Plus. The problems started a while ago (weeks), I can't watch anything except live streams in Kanaler.

If I run Kodi 17.1 on the same device SVT Play works without issues. Unfortunately there are other issues with Kodi 17.1 (performance, not related to SVT Play plugin) that force me to stay with Kodi 16.1.

Attached log file that shows me trying to watch something in "Senaste program" and then succesfully starting a live stream in Kanaler.

[kodi.txt](https://github.com/nilzen/xbmc-svtplay/files/1016782/kodi.txt)

EDIT: My github account was flagged, my post didn't show, should be OK now.

EDIT2: Seems to be fixed by https://github.com/nilzen/xbmc-svtplay/commit/5917702f0101a3080cd23f09a5bead0fb43c5f92

**Comment by linqcan** [comment] 2017-06-01 07:07
Sorry, didn't notice your comment before due to your flagged account.

I will push 4.0.49 including 5917702f0101a3080cd23f09a5bead0fb43c5f92, and you can report back when you have tried that update.

**Comment by linqcan** [comment] 2017-06-01 07:30
Created PR towards Kodi, waiting for pull.
https://github.com/xbmc/repo-plugins/pull/1233

**Closed as completed by linqcan** 2017-06-01 07:30 UTC

**Comment by psonnosp** [comment] 2017-06-01 18:14
Didn't know my account was flagged and know nothing about it, can't see any info regarding my flag either. Don't even know what it means since I'm very new to this place.
But will try the update to see if it makes a difference and let you know.

**Comment by linqcan** [comment] 2017-06-02 06:28
@psonnosp It was not your account, it was the other poster (see their comment).

Please test v4.0.49 (should be pushed by Kodi now) and get back here. Note that some listings are broken due to backend changes. I am fixing those in a separate issue.

**Comment by psonnosp** [comment] 2017-06-10 22:25
I'm at version 4.0.50 and this seem to be solved now, everything works.

Thank you! :)
