### ISSUE TITLE
Video stream stops after around 5 min

### ISSUE THREAD

**Issue by dromhost** [kodi-svtplay/xbmc-svtplay#279] opened 2022-11-24 20:08 UTC
# Problem description
Thie has been a problem for a few days.
In the beginning of every stream started, audio is a little out of sync for a few seconds. This is corrected after a while.
Any video stream from SVTPlay "Kanaler" stops after around 5 minutes.
Just before it stops, there are a few short audio glitches.

Other streams outside SVTPlay, do not seem to be affected.

# Steps to reproduce
Open "Kanaler"
Choose "SVT1" or "SVT2"
Live stream starts.
Live stream stops after around 5 minutes.
Choose the same stream again.
Live stream starts.
Live stream stops after around 5 minutes.
...

# System information
Kodi version: 19.4-Matrix 

Platform: LibreElec 10.0.3, RPi2

Plugin version: 5.1.16 

# Log

https://pastebin.ubuntu.com/p/fqZ5kM7jSp/

**Comment by linqcan** [comment] 2022-11-24 21:33
Thank you for submitting this issue!

I can reproduce it on Kodi 19.4 and Kodi 20 (beta) for some streams like "channels".  However, for others there are no issues.

My conclusion is that it has to be some kind of issue with SVT's streams and not addon or player (Kodi) related.

I have a vague memory of this happening some year ago or so and the reason was that SVT's tools produced invalid HLS streams due to an error in their stream engine. It "self-healed", from an addon POV, after a few days.

I will close this issue as there is nothing this addon can do to fix this.

**Closed as completed by linqcan** 2022-11-24 21:33 UTC
