### ISSUE TITLE
svtplay.se started using https videos

### ISSUE THREAD

**Issue by khoda** [kodi-svtplay/xbmc-svtplay#83] opened 2013-08-31 16:19 UTC
XBMC's ffmpeg is compiled without ssl support so videos are not playable. 

See http://svtplay10j-f.akamaihd.net/i/se/open/20130828/1330863-001A/SPIES_BENEATH_B-001A-a440df902c40cd28_,900,348,564,1680,2800,.mp4.csmil/master.m3u8

**Comment by linqcan** [comment] 2013-09-01 11:50
Not much we can do at the moment I suppose. Is it only new videos that don't work or have they changed for all?

**Comment by khoda** [comment] 2013-09-01 13:37
I checked some older videos and it seems they changed for all.

**Comment by DanielMalmgren** [comment] 2013-09-03 17:52
So, when xbmc starts shipping with tls-enabled ffmpeg (which I'm assuming will happen), will this addon work again straight off?

**Comment by linqcan** [comment] 2013-09-03 20:57
I don't have a clue. Guess we have to wait and see until a nightly with SSL support is live (if ever): http://forum.xbmc.org/showthread.php?tid=166897

Maybe I should blacklist the plugin for now, will talk to the XBMC add-on team.

**Comment by linqcan** [comment] 2013-09-04 09:41
I have marked the plugin as broken for now. Don't want people to install it and come complaining about it not working.

**Comment by nilzen** [comment] 2013-09-04 12:29
Seems like there's being work done in xbmc to fix ssl right now https://github.com/xbmc/xbmc/pull/3193

**Comment by linqcan** [comment] 2013-09-04 15:54
yeah, but will it be part of a maintenace release or XBMC 13?
http://forum.xbmc.org/showthread.php?tid=166897&page=2

**Comment by joelhell** [comment] 2013-09-06 09:26
The answer from SVT is a non-answer:

http://kontakt.svtplay.se/org/svt-play/d/xbmc-1/

http://kontakt.svtplay.se/org/svt-play/d/inga-avsnitt-pa-xbmc/#c318166

**Comment by linqcan** [comment] 2013-09-06 09:47
I am sorry, but what do you expect?
SVT is in no way supporting the way we are accessing their streams, hence they will never answer any questions regarding XBMC with anything else than that. SVT does **NOT** offer any API (contrary to what someone mentions in the thread).
People seem to take SVTPlay through XBMC for granted, which is wrong. This is merely a "happy hack" that will work until SVT decides otherwise.

**Comment by joelhell** [comment] 2013-09-06 12:29
I just want SVT to have a more open approach. Its suppose to be public service

**Comment by linqcan** [comment] 2013-09-15 11:07
Getting closer to a working solution it seems (no ETA) https://github.com/xbmc/xbmc/pull/3193

**Comment by nilzen** [comment] 2013-09-15 11:23
Yeah I follow that thread, hopefully it will be merged in the next window (October) and then we can add this add on to the Gotham specific add on repository.

**Comment by linqcan** [comment] 2013-10-06 22:07
Heard rumors that the plugin works again. Are those rumors true?

**Comment by DanielMalmgren** [comment] 2013-10-07 06:39
Yes, it works like a charm for me after upgrading to latest monthly (using Ubuntu unstable ppa).

**Comment by linqcan** [comment] 2013-10-07 07:44
Got a report that it worked on an ATV running Frodo 12.2 as well.

**Comment by linqcan** [comment] 2013-10-08 08:01
Will unblock the addon for now.

**Comment by nilzen** [comment] 2013-10-08 08:03
Does it work again? Has Svt removed https? I saw that xbmc/xbmc#3193 has been merged but that wont be available until next release...

**Comment by linqcan** [comment] 2013-10-08 08:21
My non-empirical research says that they seem to moved away from https. Do not know if it is temporary or not...

**Comment by linqcan** [comment] 2013-10-08 09:31
Lets leave the block for now, until something on the site breaks. The block only prevents _new_ users from installing so current users can enjoy it. "Hackers" can always download the zip from here and install it manually.

**Comment by kokangit** [comment] 2013-10-09 05:23
Still using https for "Kanaler", ie live channels.

**Comment by linqcan** [comment] 2013-10-20 10:06
So SVT explained the issue on their website (see blow in Swedish), to conclude:
- Video on demand (VOD) shows were encrypted by accident and the encryption should now be gone
- Live shows (Kanaler) will remain encrypted due to concerns from the copyright owners

XBMC 13 might include the necessary components to play encrypted files, but XBMC 12 will never. Therefore, the following is proposed:
- We remove the "broken" tag and hide "Kanaler" for now (to enable new users to install the addon).
- When preparing the addon for XBMC 13 we re-enable "Kanaler" again if encrypted streams work as intended on all/most platforms (ATV, RPI especially).

@nilzen What do you say?

From SVT:
 <pre>
Hej,
Det var en krypteringsfunktion som har slagits på av misstag. Nu ska detta vara borta på vårt VOD-material. Men av rättighetsskäl har vi blivit tvungna att slå på det på våra Kanaler.

[...]
/J

Jens Köpsén
Utvecklingsansvarig
Ons 25 sep
</pre>

**Comment by nilzen** [comment] 2013-10-20 10:31
I agree on removing the broken tag and hiding the live channels. And then we'll see if it works in Gotham (v 13) and re-add live channels again into that repo.

**Comment by emwtur** [comment] 2013-10-22 18:08
Running a Pre-Build of Gotham on my RaspBerry :-)
HD streams are running smoothly !

**Comment by linqcan** [comment] 2013-10-22 18:41
@nilzen Sent pull request to XBMC. Should re-enable the addon again but hide live channels on the start page. This concerns the frodo branch of XBMC (12.x)

**Comment by buren** [comment] 2013-10-22 19:15
nice work!

**Comment by linqcan** [comment] 2013-10-24 07:01
Oh, and to spam this thread a bit more; the addon have been downloaded over 500 000 times now.

<pre>
<addon id="plugin.video.svtplay">
<downloads>518919</downloads>
</addon>
</pre>

**Comment by nilzen** [comment] 2013-10-24 07:04
Oh nice, I think we need a "Buy us a beer"-button somewhere ;)

Where did you get those stats from?

**Comment by linqcan** [comment] 2013-10-24 07:07
Agreed!

Source: http://mirrors.xbmc.org/addons/addons_simplestats.xml

**Comment by linqcan** [comment] 2013-10-31 21:18
Closing this one now. Will open a new one for Gotham when it is applicable.

**Closed as completed by linqcan** 2013-10-31 21:18 UTC
Labels: confirmed
