### ISSUE TITLE
Not playing searched videos

### ISSUE THREAD

**Issue by kokangit** [kodi-svtplay/xbmc-svtplay#75] opened 2013-04-10 06:32 UTC
Searching for "quick". Found "Dokument inifrån - Thomas Quick del 1". Cannot play this.
Got this in xbmc.log:
20:23:27 T:102957056   ERROR: Playlist Player: skipping unplayable item: 0, path
 [plugin://plugin.video.svtplay/?url=%2Fvideo%2F321577%2Fthomas-quick-del-1&mode
=video]

I am running org.xbmc.xbmc-ATV2-ffmpeg-1.2-20130406-rev-g88a6773 and plugin 3.3.0.

**Comment by linqcan** [comment] 2013-04-10 07:02
Confirmed.

There are multiple errors here.
1. hlsurl was never initialized properly
2. The get stream functionality was created using information from fairly new programs. Older ones, like the one in the issue report, have a different bitrate schema.

Problem 1 is easily solved, and I have added some "fault handling" as well.
Problem 2 is a bit more tedious are requires analysis of a broader range of programs to ensure that the bitrate array (in the svt module) is ~~tweaked to match both new and old bitrate settings from SVT~~.

Update: If there is no stream for the manually selected bitrate then the user should receive an error dialog at least. Then the user has to decide if they want to lower the bitrate or not?

You can, however, workaround this issue by disabling the "Bandwidth selection" mechanism. Also note that this show has no ATV compatible streams (but since you are using the new ffmpeg library this won't matter to you as long as you do not have the avc1.77.30 stripping enabled).

**Comment by linqcan** [comment] 2013-04-10 08:36
Did a quick hack with better error handling/reporting:
https://github.com/linqcan/xbmc-svtplay/commit/c5c2aed49f42c02b2a6091add9c85f2b4d5ed12d

This hack does not let you play the program referenced in the issue report if you have set the bandwidth to 2500 since there are no streams that support that bandwidth. The highest available stream has bandwidth 2386. Instead this hack should show an dialog informing the user about the problem.

**Comment by linqcan** [comment] 2013-04-16 22:29
@kokangit @nilzen What about this, has anyone had time to try it yet?

**Comment by kokangit** [comment] 2013-04-17 06:11
Sorry for my delay. Yesterday I finally did and now it seems to work. Though I have not made an extensive test. Thanks for your excellent support!

**Comment by linqcan** [comment] 2013-04-17 07:46
@kokangit would you mind elaborate "working" for me? =)

**Comment by kokangit** [comment] 2013-04-17 07:52
I disabled bandwidth selection and searched for quick which was now playable.

**Comment by linqcan** [comment] 2013-04-17 07:58
Aha, ok!
Would you mind testing the non-working case also? (to see if the error handling works).

**Comment by kokangit** [comment] 2013-04-17 08:18
Here is the complete result:
- bandwidth 2500: correct error message
- bandwidth 1600: plays ok
- disabled bandwidth selection: plays ok

Seems to work!

**Comment by linqcan** [comment] 2013-04-17 08:22
Thanks!

**Comment by linqcan** [comment] 2013-04-17 15:01
@nilzen is this fault-handling mechanism something we should incorporate or can it be done in a better/easier way?

**Comment by linqcan** [comment] 2013-07-11 10:28
Accidently deleted branch, new branch with fix is now: https://github.com/linqcan/xbmc-svtplay/tree/errorhandling

**Comment by linqcan** [comment] 2013-10-20 09:56
Will look into this again when doing some refactoring the upcoming week (hopefully).

**Comment by linqcan** [comment] 2013-10-31 21:24
This issue seems to be fixed after merging #86. Error messages are shown as described above by the author. Closing this one. Please create a new one if errors still exist.

**Closed as completed by linqcan** 2013-10-31 21:24 UTC
Labels: confirmed, fix exists
