### ISSUE TITLE
Subtitles for hearing impaired is not working

### ISSUE THREAD

**Issue by funnybunnies** [kodi-svtplay/xbmc-svtplay#227] opened 2019-02-12 19:03 UTC
Basically what the title said.
Subtitles option for hearing impaired is not working. That is, subtitles when they speak Swedish in the videos. 

I tried to enable the subtitles by turning it on in the subtitle settings but it did not work.

# Steps to reproduce

# System information
Kodi version: 

Platform: 

Plugin version: 

# Log

**Comment by linqcan** [comment] 2019-02-12 19:41
Was there no issue in the end?

**Comment by funnybunnies** [comment] 2019-02-13 03:41
I realized I should reopen it. I tried to reply to email but I guess I am still very noob. :) 

So, here's a little more information, what I wrote in email:

Oh there still is but I felt I should have clarified a little bit because there's those that works and there's those that won't. This one won't work for example

https://www.svtplay.se/video/21054640/veckans-brott/veckans-brott-redaktionen-avsnitt-15?start=auto&tab=2019

Maybe it is of help?

**Comment by linqcan** [comment] 2019-02-13 12:52
Strange, I can get that episode to work. 
Have you tried toggling subtitles on/off in Kodi? (using the player UI or key "t" on a keyboard)

**Comment by payano** [comment] 2019-03-12 20:28
I have sort of the same problem too, if I watch for example channel 1 in the category channels, i don't get subtitles, is it working for you?

**Comment by linqcan** [comment] 2019-05-08 20:45
I can reproduce the issue on Android using Kodi 18.2 but only for live channels. Recorded content like 'Rapport" has working subtitles. This is likely due to the use of different subtitle formats for live VS recorded content. 

Edit: Kodi doesn't seem to support the subtitle format used for live channels ("Kanaler"/"Channels" sub menu). Nothing we can do, maybe future releases of Kodi will when they update their ffmpeg version.

**Comment by funnybunnies** [comment] 2019-05-09 10:19
I have now watched a few shows and it is in my note that the subs is not synced well. I am deaf so I can't say about the sync with the talking part, but I could see it clearly when there's hard subs and soft subs going on same time. Often the soft sub would lay over the hard subs, which is not really correct. 

(hard sub = when foreign people talking, soft sub = when Swedish is spoken)

Alas, I do not remember which shows, but it was some documentary I can recall.

**Comment by linqcan** [comment] 2019-05-10 22:16
You can manually sync subtitles using the "offset" setting in Kodi's subtitle settings. Maybe this can help?
The SVT addon can't do anything about it I'm afraid.

**Comment by linqcan** [comment] 2019-05-25 19:18
@funnybunnies Did you manage to sync the subtitles using the "offset" setting?

**Comment by funnybunnies** [comment] 2019-05-26 09:49
I haven't used the app because 1. I do not want to spoil my self fiddling and 2. it is hard for me as deaf to judge when they are talking etcetera (just going by mouth is not always correct because you have to guess what they are talking about TOO). Sorry!

**Comment by linqcan** [comment] 2019-06-09 11:51
OK, I will open a new issue for missing subtitles for "Kanaler" (might be fixed in Kodi 19) and close this one.

**Closed as completed by linqcan** 2019-06-09 11:51 UTC
Labels: kodi issue
