### ISSUE TITLE
A-Z listing not working

### ISSUE THREAD

**Issue by keab** [kodi-svtplay/xbmc-svtplay#174] opened 2016-12-06 19:44 UTC
The A-Ö listing is still not working properly in 4.0.37.  I only see a list of unnamed folders. If I enter one of the folders it contains streams that can be played but with partly strange names e.g. "Avsnitt1(S1E1)"

Thanks for a great add-on!

**Comment by linqcan** [comment] 2016-12-08 08:28
Could you provide some more details?

* Are all folders unnamed?
* Do you use A-Z grouping?
* If not, could you try that and see if the issue is seen there too?

**Comment by linqcan** [comment] 2016-12-08 16:26
Just did a try here (both gruoped and non-grouped) and it worked fine. See screenshot below.
Is this still an issue for you?

![screenshot_2016-12-08_17-23-30](https://cloud.githubusercontent.com/assets/832984/21017940/5caa67a8-bd6b-11e6-9f56-0ea6f0ddc4ba.png)

**Comment by keab** [comment] 2016-12-09 18:48
I found the problem , somehow I had changed the view setting from View:List to View:Wide. Returning that setting gave me named programs or A-Z as expected. 
It would probably be better if both settings were "allowed", but I won't complain.  
Thanks for helping.

**Comment by linqcan** [comment] 2016-12-09 18:54
That's unfortunately a Kodi related "issue", the reason is that it assumes
some meta data that we are not supplying. Will add a reminder to check what
meta data it is to see if there is something the plug in can do to mitigate
this. Closing this issue.

**Closed as completed** 2016-12-10 14:54 UTC
